version: '3.8'

services:
  app:
    image: node:14
    container_name: app_container
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    command: "npm start"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: db_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    container_name: redis_container
    ports:
      - "6379:6379"