AWSTemplateFormatVersion: '2010-09-09'
Description: Infraestructura AWS con EC2 y S3 para el Learner Lab

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c02fb55956c7d316 # Amazon Linux 2 en us-east-1
      IamInstanceProfile: !Ref LabRoleInstanceProfile
      Tags:
        - Key: Name
          Value: LearnerLabEC2Instance

  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub learner-lab-bucket-${AWS::AccountId}
      Tags:
        - Key: Name
          Value: LearnerLabS3Bucket

  LabRoleInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - LabRole